language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf
  - sudo apt-get install -y libmaxminddb0 libmaxminddb-dev mmdb-bin
before_script:
  - cd ../
  - git clone https://github.com/mruby/mruby.git
  - cd mruby
  - cp -fp ../mruby-maxminddb/.travis_build_config.rb build_config.rb
  - sudo wget -N http://geolite.maxmind.com/download/geoip/database/GeoLite2-City.mmdb.gz
  - sudo gunzip GeoLite2-City.mmdb.gz
  - sudo mv GeoLiteCity.dat /tmp/
script:
  - make all test
