language: c
compiler:
  - gcc
  - clang
before_install:
  - sudo add-apt-repository -y ppa:maxmind/ppa
  - sudo apt-get -qq update
install:
  - sudo apt-get -qq install rake bison git gperf
  - sudo apt-get install -y libmaxminddb0 libmaxminddb-dev mmdb-bin
before_script:
  - git clone https://github.com/mruby/mruby.git
  - cp -fp .travis_build_config.rb mruby/build_config.rb
  - cd mruby
script:
  - make all test
